<project name="scriptcraft" default="package" basedir=".">
  <description>Builds the scriptcraft.jar file - a plugin for bukkit</description>
  <!-- ScriptCraft works with:
       * CanaryMod
       * Bukkit
       * Glowstone (which is bukkit-compatible)
       * Spigot (which is bukkit-compatible)
  -->

  <property name="build" location="target/classes"/>
  <property name="dist" location="target/" />
  <property name="minecraft.dir" location="${dist}/minecraft" />
  <property name="js-plugins-dir" value="scriptcraft"/>
  <property name="http.agent" value="'Walter'" />

<!--  <property name="lib.canary" location="lib/canarymod-1.8.0.jar"/>-->
  <property name="lib.bukkit" location="lib/spigot-1.21.4.jar"/>

  <macrodef name="jscript">
    <attribute name="src"/>
    <attribute name="out"/>
    <attribute name="err"/>
    <attribute name="lib"/>
    <element name="js-args" implicit="yes" optional="true"/>
    <sequential>
<!--      <echo message="cp=${build}:${lib.canary}:${lib.bukkit}"></echo>-->
      <echo message="src=@{src} out=@{out} err=@{err}"></echo>
      <java classname="jscript" 
	    failonerror="true"
	    fork="true" output="@{out}"  error="@{err}">
	<classpath>
          <pathelement path="${build}"/>      
	  <pathelement path="@{lib}"/>
	</classpath>
      <arg value="@{src}"/>
      <js-args/>
      </java>
    </sequential>
  </macrodef>

  <target name="zip_js" depends="zip_lib, zip_modules, zip_plugins">
  </target>

  <target name="copy-js" >
<!--  <target name="copy-js" depends="gen-events-helper-bukkit">-->
    <copy todir="${dist}/js">
      <fileset dir="src/main/js"/>
    </copy>
  </target>

  <target name="zip_lib" depends="copy-js">
    <delete file="${build}/lib.zip"/>
    <zip destfile="${build}/lib.zip" 
         basedir="${dist}/js" 
         excludes="modules/**, plugins/**,">
    </zip>
  </target>

  <target name="init">
    <property file="build.local.properties"/>
    <tstamp>
      <format property="DSTAMP"
              pattern="yyyy-MM-dd"
              locale="en,UK"/>
    </tstamp>
    <mkdir dir="${build}"/>

    <available file="${dist}/js/modules/underscore.js" property="underscore.present"/>
    <available file="${dist}/js/modules/babel.js" property="babel.present"/>
  </target>

  <target name="compile-docs" depends="init">
    <javac includeantruntime="false" srcdir="src/docs/java" destdir="${build}"> </javac>
  </target>

<!--  <target name="gen-events-helper-bukkit" depends="compile-docs,init">-->
<!--    <mkdir dir="${dist}/js/lib"/>-->
<!--    <jscript src="src/docs/js/generateEventsHelper.js"-->
<!--             out="${dist}/js/lib/events-helper-bukkit.js"-->
<!--             lib="${lib.bukkit}"-->
<!--             err="${dist}/gen-events-bukkit-error.log">-->
<!--      <arg value="SpigotMC"/>-->
<!--      <arg value="${lib.bukkit}"/>-->
<!--      <arg value="blockBreak"/>-->
<!--      <arg value="org.bukkit.event.block.BlockBreakEvent"/>-->
<!--    </jscript>-->
<!--  </target>-->

  <target name="get_babel" depends="copy-js" unless="babel.present">
    <!-- download babel -->
    <get src="https://github.com/babel/babel-standalone/releases/download/release-6.26.0/babel.js"
	 verbose="true"
	 ignoreerrors="true"
	 dest="${dist}/js/modules/babel.js"/>
  </target>

  <target name="get_underscore" depends="copy-js" unless="underscore.present">
    <!-- download underscore -->
    <get src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js"
	 verbose="true"
	 ignoreerrors="true"
	 dest="${dist}/js/modules/underscore.js"/>
  </target>

  <target name="zip_modules" depends="copy-js, get_underscore, get_babel">
    <delete file="${build}/modules.zip"/>
    <zip destfile="${build}/modules.zip" 
         basedir="${dist}/js" 
         excludes="lib/**, plugins/**,">
    </zip>
  </target>

  <target name="zip_plugins" depends="copy-js">
    <delete file="${build}/plugins.zip"/>
    <zip destfile="${build}/plugins.zip" 
         basedir="${dist}/js"
         excludes="lib/**, modules/**">
    </zip>
  </target>
  
</project>
