name: ScriptCraft-Reforged
version: ${version}
main: com.ar.dann.scriptCraft.ScriptCraftPlugin
api-version: ${spigot.api.version}
commands:
  scriptcraft:
    description: Displays infor about the ScriptCraft Reforged
    usage: /<command>
    permission: scriptcraft.about
    permission-message: You don't have <permission> permission.
  js:
    description: Evaluate Javascript.
    usage: /<command> Javascript code
    permission: scriptcraft.evaluate
    permission-message: You don't have <permission> permission.
  jsp:
    description: Run a Javascript plugin command.
    usage: /<command> command-name command-parameters
    permission: scriptcraft.proxy
    permission-message: You don't have <permission> permission.



permissions:
   scriptcraft.*:
        description: Gives access to all scriptcraft comands
        children:
                scriptcraft.evaluate: true
                scriptcraft.proxy: true
   scriptcraft.evaluate:
        description: Allows you to evaluate javascript code
        default: op
   scriptcraft.proxy:
        description: Allows you to run a javascript command blessed by the operator
        default: true